---
engines:
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- ruby-units.gemspec
- bin/
- spec/
