inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - ruby-units.gemspec
    - bin/*
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/LineLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/ruby-units.rb'
Naming/MethodParameterName:
  Enabled: false
Style/FormatString:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
