AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - ruby-units.gemspec
    - bin/*
Style/CaseEquality:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/ruby-units.rb'
Style/FormatString:
  Enabled: false
Style/DateTime:
  Enabled: false
