require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - ruby-units.gemspec
    - bin/*
Style/CaseEquality:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/ruby-units.rb'
Naming/MethodParameterName:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/DateTime:
  Enabled: false
